
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start
    depends_on:
      - backend-python

  backend-python:
    build: ./backend-python
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 76773321
    ports:
      - "5433:5432"

volumes:
  pgdata:
